repository: chiara-paci/gianozia
baseurl: gianozia
url: https://chiara-paci.github.io
gems: ["jemoji"]

plugins:
  - jemoji

exclude: [elaborazione,old,nonmigrate]

collections:
  documents:
    output: true

